### ISSUE TITLE
Option[String] is broken

### ISSUE THREAD

**Issue by mikaelstaldal** [GenslerAppsPod/scalavro#29]
After commit https://github.com/GenslerAppsPod/scalavro/commit/9997bde0a4cda2fa3de2e481fb7fca77b4162bfa by @bradcfisher the String type is now ["null","string"] instead of "string" as before. Also, Option[String] is now ["null",["null","string"]] which is not valid.

**Comment by dyk** [comment]
I think the String type is now ` ["null","string"]` on purpose. I'll fix `Option[String]`
