### ISSUE TITLE
Dependency to slf4j-simple should be in test scope only.

### ISSUE THREAD

**Issue by mikaelstaldal** [GenslerAppsPod/scalavro#44]
The dependency to slf4j-simple should be in test scope only:

 "org.slf4j" % "slf4j-simple" % Common.SLF4J_VERSION % "test"

**Comment by bradcfisher** [comment]
I've updated the dependencies so the slf4j-api is used for compile and slf4j-simple is only used for test.  Should resolve the problem, closing issue.

**Comment by mikaelstaldal** [comment]
Yes, thanks.
